export const Fakedata = [
    {
        "_id": "623853b2614ad5aba311fdd11",
        "index": 0,
        "picture": "https://i.ibb.co/ZBB4TMd/google-1-1-1.png",
        "job_title": "Technical Database Engineer",
        "company_name": "Google LLC",
        "remote": "Remote",
        "full_time": "Onsite",
        "location": "Dhaka, Bangladesh",
        "location_img": "https://i.ibb.co/MPt6JPk/Frame-4.png",
        "salary": "100K - 150K",
        "salary_img": "https://i.ibb.co/0qqvhXk/Frame.png",
        "job_description": "A UI/UX (User Interface/User Experience) designer is responsible for designing and creating engaging and effective interfaces for software and web applications. This includes designing the layout, visual design, and interactivity of the user interface.",
        "job_responsibility": " Collaborating with cross-functional teams: UI/UX designers often work closely with other teams, including product management, engineering, and marketing, to ensure that the user interface is aligned with business and technical requirements. You will need to be able to effectively communicate your design ideas and gather feedback from other team members.",
        "educational_requirements": "Bachelor degree to complete any reputational university.",
        "experiences": "2-3 Years in this field.",
        "phone": "01750-00 00 00",
        "email": "info@gmail.com",
        "address": "Dhanmondi 32, SukrabadDhaka, Bangladesh"
    },
    {
        "_id": "623853b2578e9e6ad1ae0dd52",
        "index": 1,
        "picture": "https://i.ibb.co/GWjjQLt/netflix-4-1.png",
        "job_title": "Senior Product Designer",
        "company_name": "Netflix",
        "remote": "Full Time",
        "full_time": "Onsite",
        "location": "Dhaka, Bangladesh",
        "location_img": "https://i.ibb.co/MPt6JPk/Frame-4.png",
        "salary": "100K - 150K",
        "salary_img": "https://i.ibb.co/0qqvhXk/Frame.png",
        "job_description": "A UI/UX (User Interface/User Experience) designer is responsible for designing and creating engaging and effective interfaces for software and web applications. This includes designing the layout, visual design, and interactivity of the user interface.",
        "job_responsibility": " Collaborating with cross-functional teams: UI/UX designers often work closely with other teams, including product management, engineering, and marketing, to ensure that the user interface is aligned with business and technical requirements. You will need to be able to effectively communicate your design ideas and gather feedback from other team members.",
        "educational_requirements": "Bachelor degree to complete any reputational university.",
        "experiences": "2-3 Years in this field.",
        "phone": "01750-00 00 00",
        "email": "info@gmail.com",
        "address": "Dhanmondi 32, Sukrabad Dhaka, Bangladesh"
    },
    {
        "_id": "623853b21fb149d2ee7b76c73",
        "index": 2,
        "picture": "https://i.ibb.co/zPGh2LS/tesla-9-1.png",
        "job_title": "Software Engineer",
        "company_name": "Tesla",
        "remote": "Remote",
        "full_time": "Full Time",
        "onsite": "Onsite",
        "location": "Dhaka, Bangladesh",
        "location_img": "https://i.ibb.co/MPt6JPk/Frame-4.png",
        "salary": "100K - 150K",
        "salary_img": "https://i.ibb.co/0qqvhXk/Frame.png",
        "job_description": "A UI/UX (User Interface/User Experience) designer is responsible for designing and creating engaging and effective interfaces for software and web applications. This includes designing the layout, visual design, and interactivity of the user interface.",
        "job_responsibility": " Collaborating with cross-functional teams: UI/UX designers often work closely with other teams, including product management, engineering, and marketing, to ensure that the user interface is aligned with business and technical requirements. You will need to be able to effectively communicate your design ideas and gather feedback from other team members.",
        "educational_requirements": "Bachelor degree to complete any reputational university.",
        "experiences": "2-3 Years in this field.",
        "phone": "01750-00 00 00",
        "email": "info@gmail.com",
        "address": "Dhanmondi 32, SukrabadDhaka, Bangladesh"
    },
    {
        "_id": "623853b2e91c8de578c9245e4",
        "index": 3,
        "picture": "https://i.ibb.co/KqM6zP1/Untitled-1.png",
        "job_title": "Technical Database Engineer",
        "company_name": "Twiter",
        "remote": "Remote",
        "full_time": "Full Time",
        "onsite": "Onsite",
        "location": "Dhaka, Bangladesh",
        "location_img": "https://i.ibb.co/MPt6JPk/Frame-4.png",
        "salary": "100K - 150K",
        "salary_img": "https://i.ibb.co/0qqvhXk/Frame.png",
        "job_description": "A UI/UX (User Interface/User Experience) designer is responsible for designing and creating engaging and effective interfaces for software and web applications. This includes designing the layout, visual design, and interactivity of the user interface.",
        "job_responsibility": " Collaborating with cross-functional teams: UI/UX designers often work closely with other teams, including product management, engineering, and marketing, to ensure that the user interface is aligned with business and technical requirements. You will need to be able to effectively communicate your design ideas and gather feedback from other team members.",
        "educational_requirements": "Bachelor degree to complete any reputational university.",
        "experiences": "2-3 Years in this field.",
        "phone": "01750-00 00 00",
        "email": "info@gmail.com",
        "address": "Dhanmondi 32, SukrabadDhaka, Bangladesh"
    },
    {
        "_id": "623853b2e91c8de578c9245e5",
        "index": 3,
        "picture": "https://i.ibb.co/KqM6zP1/Untitled-1.png",
        "job_title": "Technical Database Engineer",
        "company_name": "Twiter",
        "remote": "Remote",
        "full_time": "Remote",
        "onsite": "Onsite",
        "location": "Dhaka, Bangladesh",
        "location_img": "https://i.ibb.co/MPt6JPk/Frame-4.png",
        "salary": "100K - 150K",
        "salary_img": "https://i.ibb.co/0qqvhXk/Frame.png",
        "job_description": "A UI/UX (User Interface/User Experience) designer is responsible for designing and creating engaging and effective interfaces for software and web applications. This includes designing the layout, visual design, and interactivity of the user interface.",
        "job_responsibility": " Collaborating with cross-functional teams: UI/UX designers often work closely with other teams, including product management, engineering, and marketing, to ensure that the user interface is aligned with business and technical requirements. You will need to be able to effectively communicate your design ideas and gather feedback from other team members.",
        "educational_requirements": "Bachelor degree to complete any reputational university.",
        "experiences": "2-3 Years in this field.",
        "phone": "01750-00 00 00",
        "email": "info@gmail.com",
        "address": "Dhanmondi 32, SukrabadDhaka, Bangladesh"
    },
    {
        "_id": "623853b2e91c8de578c9245e6",
        "index": 3,
        "picture": "https://i.ibb.co/KqM6zP1/Untitled-1.png",
        "job_title": "Technical Database Engineer",
        "company_name": "Twiter",
        "remote": "Remote",
        "full_time": "Remote",
        "onsite": "Onsite",
        "location": "Dhaka, Bangladesh",
        "location_img": "https://i.ibb.co/MPt6JPk/Frame-4.png",
        "salary": "100K - 150K",
        "salary_img": "https://i.ibb.co/0qqvhXk/Frame.png",
        "job_description": "A UI/UX (User Interface/User Experience) designer is responsible for designing and creating engaging and effective interfaces for software and web applications. This includes designing the layout, visual design, and interactivity of the user interface.",
        "job_responsibility": " Collaborating with cross-functional teams: UI/UX designers often work closely with other teams, including product management, engineering, and marketing, to ensure that the user interface is aligned with business and technical requirements. You will need to be able to effectively communicate your design ideas and gather feedback from other team members.",
        "educational_requirements": "Bachelor degree to complete any reputational university.",
        "experiences": "2-3 Years in this field.",
        "phone": "01750-00 00 00",
        "email": "info@gmail.com",
        "address": "Dhanmondi 32, SukrabadDhaka, Bangladesh"
    }
]